plugins { id 'com.android.application' }

android {
    namespace 'com.gabriel.bydassistant'
    compileSdk 35

    defaultConfig {
        applicationId 'com.gabriel.bydassistant'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '0.2-gold'
    }
}

dependencies {
    implementation 'com.alphacephei:vosk-android:0.3.47@aar'
    implementation 'net.java.dev.jna:jna:5.13.0@aar'
}
